### ISSUE TITLE
Error: Illegal value for `line` ; Parameter doesnt get logged

### ISSUE THREAD

**Issue by 1muen** [Chakroun-Anas/turbo-console-log#229]
VS-Code Insider
```
Version: 1.87.0-insider (user setup)
Commit: 9db1b0571e119289a2264971bdac75793965e063
Date: 2024-02-07T05:47:25.686Z
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: shouldnt matter
```

chakrounanas.turbo-console-log: `2.10.4`

Try the following TypeScript code:
```
const response = await axiosPost(url, test, {
    headers: { Authorization: `Bearer ${token}` },
});
```
It works with token but not with url or test.
Mark test and press the key combination that should put the console.log in your code and it doesnt work, instead it prints this Error Message and stack trace in the Extension Host log:
```
2024-02-07 16:05:34.881 [error] Error: Illegal value for `line`
	at b.t (/home/1muen/.vscode-server-insiders/bin/9db1b0571e119289a2264971bdac75793965e063/out/vs/workbench/api/node/extensionHostProcess.js:149:961)
	at Object.lineAt (/home/1muen/.vscode-server-insiders/bin/9db1b0571e119289a2264971bdac75793965e063/out/vs/workbench/api/node/extensionHostProcess.js:149:90)
	at xt.isEmptyBlockContext (/home/1muen/.vscode-server-insiders/extensions/chakrounanas.turbo-console-log-2.10.4/out/extension.js:32:99)
	at xt.msg (/home/1muen/.vscode-server-insiders/extensions/chakrounanas.turbo-console-log-2.10.4/out/extension.js:38:909)
	at /home/1muen/.vscode-server-insiders/extensions/chakrounanas.turbo-console-log-2.10.4/out/extension.js:40:4040
	at Object.edit (/home/1muen/.vscode-server-insiders/bin/9db1b0571e119289a2264971bdac75793965e063/out/vs/workbench/api/node/extensionHostProcess.js:152:20588)
	at /home/1muen/.vscode-server-insiders/extensions/chakrounanas.turbo-console-log-2.10.4/out/extension.js:40:4029
	at Generator.next (<anonymous>)
	at /home/1muen/.vscode-server-insiders/extensions/chakrounanas.turbo-console-log-2.10.4/out/extension.js:1:847
	at new Promise (<anonymous>)
	at _e (/home/1muen/.vscode-server-insiders/extensions/chakrounanas.turbo-console-log-2.10.4/out/extension.js:1:667)
	at handler (/home/1muen/.vscode-server-insiders/extensions/chakrounanas.turbo-console-log-2.10.4/out/extension.js:40:3726)
	at /home/1muen/.vscode-server-insiders/extensions/chakrounanas.turbo-console-log-2.10.4/out/extension.js:42:4048
	at s.h (/home/1muen/.vscode-server-insiders/bin/9db1b0571e119289a2264971bdac75793965e063/out/vs/workbench/api/node/extensionHostProcess.js:150:177252)
	at s.$executeContributedCommand (/home/1muen/.vscode-server-insiders/bin/9db1b0571e119289a2264971bdac75793965e063/out/vs/workbench/api/node/extensionHostProcess.js:150:178112)
	at d.S (/home/1muen/.vscode-server-insiders/bin/9db1b0571e119289a2264971bdac75793965e063/out/vs/workbench/api/node/extensionHostProcess.js:147:5519)
	at d.Q (/home/1muen/.vscode-server-insiders/bin/9db1b0571e119289a2264971bdac75793965e063/out/vs/workbench/api/node/extensionHostProcess.js:147:5285)
	at d.M (/home/1muen/.vscode-server-insiders/bin/9db1b0571e119289a2264971bdac75793965e063/out/vs/workbench/api/node/extensionHostProcess.js:147:4375)
	at d.L (/home/1muen/.vscode-server-insiders/bin/9db1b0571e119289a2264971bdac75793965e063/out/vs/workbench/api/node/extensionHostProcess.js:147:3454)
	at m.value (/home/1muen/.vscode-server-insiders/bin/9db1b0571e119289a2264971bdac75793965e063/out/vs/workbench/api/node/extensionHostProcess.js:147:2241)
	at r.y (/home/1muen/.vscode-server-insiders/bin/9db1b0571e119289a2264971bdac75793965e063/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
	at r.fire (/home/1muen/.vscode-server-insiders/bin/9db1b0571e119289a2264971bdac75793965e063/out/vs/workbench/api/node/extensionHostProcess.js:80:2119)
	at n.fire (/home/1muen/.vscode-server-insiders/bin/9db1b0571e119289a2264971bdac75793965e063/out/vs/workbench/api/node/extensionHostProcess.js:105:14050)
	at m.value (/home/1muen/.vscode-server-insiders/bin/9db1b0571e119289a2264971bdac75793965e063/out/vs/workbench/api/node/extensionHostProcess.js:173:8047)
	at r.y (/home/1muen/.vscode-server-insiders/bin/9db1b0571e119289a2264971bdac75793965e063/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
	at r.fire (/home/1muen/.vscode-server-insiders/bin/9db1b0571e119289a2264971bdac75793965e063/out/vs/workbench/api/node/extensionHostProcess.js:80:2119)
	at n.fire (/home/1muen/.vscode-server-insiders/bin/9db1b0571e119289a2264971bdac75793965e063/out/vs/workbench/api/node/extensionHostProcess.js:105:14050)
	at s.z (/home/1muen/.vscode-server-insiders/bin/9db1b0571e119289a2264971bdac75793965e063/out/vs/workbench/api/node/extensionHostProcess.js:105:17115)
	at m.value (/home/1muen/.vscode-server-insiders/bin/9db1b0571e119289a2264971bdac75793965e063/out/vs/workbench/api/node/extensionHostProcess.js:105:15567)
	at r.y (/home/1muen/.vscode-server-insiders/bin/9db1b0571e119289a2264971bdac75793965e063/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
	at r.fire (/home/1muen/.vscode-server-insiders/bin/9db1b0571e119289a2264971bdac75793965e063/out/vs/workbench/api/node/extensionHostProcess.js:80:2119)
	at m.acceptChunk (/home/1muen/.vscode-server-insiders/bin/9db1b0571e119289a2264971bdac75793965e063/out/vs/workbench/api/node/extensionHostProcess.js:105:11824)
	at m.value (/home/1muen/.vscode-server-insiders/bin/9db1b0571e119289a2264971bdac75793965e063/out/vs/workbench/api/node/extensionHostProcess.js:105:11111)
	at r.y (/home/1muen/.vscode-server-insiders/bin/9db1b0571e119289a2264971bdac75793965e063/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
	at r.fire (/home/1muen/.vscode-server-insiders/bin/9db1b0571e119289a2264971bdac75793965e063/out/vs/workbench/api/node/extensionHostProcess.js:80:2119)
	at r.z (/home/1muen/.vscode-server-insiders/bin/9db1b0571e119289a2264971bdac75793965e063/out/vs/workbench/api/node/extensionHostProcess.js:170:19768)
	at r.acceptFrame (/home/1muen/.vscode-server-insiders/bin/9db1b0571e119289a2264971bdac75793965e063/out/vs/workbench/api/node/extensionHostProcess.js:170:19574)
	at i.n (/home/1muen/.vscode-server-insiders/bin/9db1b0571e119289a2264971bdac75793965e063/out/vs/workbench/api/node/extensionHostProcess.js:170:18073)
	at /home/1muen/.vscode-server-insiders/bin/9db1b0571e119289a2264971bdac75793965e063/out/vs/workbench/api/node/extensionHostProcess.js:170:15293
	at Socket.y (/home/1muen/.vscode-server-insiders/bin/9db1b0571e119289a2264971bdac75793965e063/out/vs/workbench/api/node/extensionHostProcess.js:170:13198)
	at Socket.emit (node:events:514:28)
	at addChunk (node:internal/streams/readable:324:12)
	at readableAddChunk (node:internal/streams/readable:297:9)
	at Readable.push (node:internal/streams/readable:234:10)
	at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

**Comment by Chakroun-Anas** [comment]
Hi @1muen, thank you for reporting this issue and providing the detailed information!

I’ve tested the provided code snippet with the latest version of Turbo Console Log (`v2.10.8`) but was unable to reproduce the issue. It seems this might have been resolved in one of the recent updates.

Could you please update your extension to the latest version and let me know if the issue persists? If it does, any additional details about your setup or steps to reproduce would be very helpful.

Thanks again for your support and sorry for the very late response! 😊

**Comment by 1muen** [comment]
Its not reproducible anymore. Thank you! :)
